services:
  db:
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_DB=db
    - USERMAP_UID=1000
    - USERMAP_GID=1000
    image: akretion/voodoo-postgresql
    volumes:
    - .db/data/:/var/lib/postgresql/data
    - .db/socket/:/var/run/postgresql/
  mailcatcher:
    image: akretion/lightweight-mailcatcher
    ports:
    - 1280:1080
    - 1225:1025
  odoo:
    environment:
    - PYTHONDONTWRITEBYTECODE=True
    extends:
      file: docker-compose.yml
      service: odoo
    links:
    - db
    ports:
    - 7069:8069 # Odoo
    - 7032:5432 # PostgreSQL
    volumes:
    - .:/workspace
    - .db/socket/:/var/run/postgresql/
    - /home/sylvain/.voodoo/shared:/home/sylvain/.voodoo/shared
version: '2'
