networks:
  default:
    external:
      name: dy
services:
  db:
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_DB=db
    image: akretion/voodoo-postgresql
    volumes:
    - .db/data/:/var/lib/postgresql/data
    - .db/socket/:/var/run/postgresql/
  odoo:
    environment:
    - PYTHONDONTWRITEBYTECODE=True
    - USERMAP_UID=1000
    - USERMAP_GID=1000
    - VIRTUAL_HOST=instance_grap_9_docky.dy
    - VIRTUAL_PORT=8069
    - MAINTAINER_QUALITY_TOOLS=/home/${USER}/.docky/shared/maintainer_quality_tools
    image: akretion/voodoo:latest
    links:
    - db
    volumes:
    - .:/workspace
    - .db/socket/:/var/run/postgresql/
    - /bin/ping:/bin/ping
    - /opt/grap_dev/backup/GRP/:/workspace/backup
    - /home/sylvain/.voodoo/shared:/home/sylvain/.voodoo/shared
version: '2'
